import { boolean, integer, pgTable, serial, varchar, text, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const candidates = pgTable('candidates', {
  id: serial('id').primaryKey(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  phone: varchar('phone', { length: 20 }).notNull(),
  linkedinUrl: varchar('linkedin_url', { length: 500 }).notNull(),
  resumePath: varchar('resume_path', { length: 500 }).notNull(),
  college: varchar('college', { length: 255 }),
  graduationYear: varchar('graduation_year', { length: 10 }),
  degreeBranch: varchar('degree_branch', { length: 255 }),
  referralSource: varchar('referral_source', { length: 255 }),
  accountStatus: varchar('account_status', { length: 50 }).default('inactive'),
  paymentStatus: varchar('payment_status', { length: 50 }).default('pending'),
  paymentId: varchar('payment_id', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow(),
});

export const companies = pgTable('companies', {
  id: serial('id').primaryKey(),
  companyName: varchar('company_name', { length: 255 }).notNull(),
  websiteUrl: varchar('website_url', { length: 500 }).notNull(),
  industry: varchar('industry', { length: 100 }),
  companySize: varchar('company_size', { length: 50 }),
  companyStage: varchar('company_stage', { length: 50 }),
  rolesHiringFor: text('roles_hiring_for'),
  contactName: varchar('contact_name', { length: 255 }).notNull(),
  contactRole: varchar('contact_role', { length: 255 }),
  contactEmail: varchar('contact_email', { length: 255 }).notNull(),
  contactPhone: varchar('contact_phone', { length: 20 }),
  contactLinkedin: varchar('contact_linkedin', { length: 500 }),
  problemTitle: varchar('problem_title', { length: 500 }).notNull(),
  problemDescription: text('problem_description'),
  businessContext: text('business_context').notNull(),
  coreTask: text('core_task').notNull(),
  expectedDeliverables: text('expected_deliverables'),
  preferredStack: varchar('preferred_stack', { length: 255 }),
  techStack: varchar('tech_stack', { length: 255 }),
  toolRestrictions: varchar('tool_restrictions', { length: 500 }),
  difficultyLevel: varchar('difficulty_level', { length: 50 }),
  nominateJury: varchar('nominate_jury', { length: 20 }),
  juryName: varchar('jury_name', { length: 255 }),
  juryDesignation: varchar('jury_designation', { length: 255 }),
  customEvalCriteria: text('custom_eval_criteria'),
  strongSolutionCriteria: text('strong_solution_criteria'),
  hiringIntent: varchar('hiring_intent', { length: 100 }),
  preferredTimeline: varchar('preferred_timeline', { length: 50 }),
  approxOpenings: varchar('approx_openings', { length: 50 }),
  numberRoles: varchar('number_roles', { length: 50 }),
  skillsLookingFor: text('skills_looking_for'),
  finalRoundAttendeeName: varchar('final_round_attendee_name', { length: 255 }),
  finalRoundAttendeeRole: varchar('final_round_attendee_role', { length: 255 }),
  suggestChallenge: boolean('suggest_challenge').default(false),
  confirmations: text('confirmations'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const companyAuditionDrafts = pgTable('company_audition_drafts', {
  id: serial('id').primaryKey(),
  status: varchar('status', { length: 50 }).notNull().default('lead_captured'),
  contactName: varchar('contact_name', { length: 255 }).notNull(),
  companyName: varchar('company_name', { length: 255 }).notNull(),
  workEmail: varchar('work_email', { length: 255 }).notNull(),
  emailVerifiedAt: timestamp('email_verified_at'),
  verificationCodeHash: varchar('verification_code_hash', { length: 255 }),
  verificationExpiresAt: timestamp('verification_expires_at'),
  websiteUrl: varchar('website_url', { length: 500 }),
  companySize: varchar('company_size', { length: 50 }),
  industry: varchar('industry', { length: 100 }),
  rolesHiringFor: text('roles_hiring_for'),
  numberRoles: varchar('number_roles', { length: 50 }),
  techStack: varchar('tech_stack', { length: 255 }),
  skillsToEvaluate: text('skills_to_evaluate'),
  problemContext: text('problem_context'),
  strongSolutionCriteria: text('strong_solution_criteria'),
  suggestChallenge: boolean('suggest_challenge').default(false),
  generatedDraftJson: text('generated_draft_json'),
  editedDraftJson: text('edited_draft_json'),
  generationCount: integer('generation_count').notNull().default(0),
  lastGeneratedAt: timestamp('last_generated_at'),
  finalRoundAttendeeName: varchar('final_round_attendee_name', { length: 255 }),
  finalRoundAttendeeRole: varchar('final_round_attendee_role', { length: 255 }),
  preferredTimeline: varchar('preferred_timeline', { length: 50 }),
  contactLinkedin: varchar('contact_linkedin', { length: 500 }),
  submittedAt: timestamp('submitted_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const juryMembers = pgTable('jury_members', {
  id: serial('id').primaryKey(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  linkedinUrl: varchar('linkedin_url', { length: 500 }).notNull(),
  currentRole: varchar('current_role', { length: 255 }),
  company: varchar('company', { length: 255 }),
  domainExpertise: text('domain_expertise'),
  yearsExperience: varchar('years_experience', { length: 20 }),
  availability: varchar('availability', { length: 50 }),
  motivation: text('motivation'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const candidateUsers = pgTable('candidate_users', {
  id: serial('id').primaryKey(),
  firebaseUid: varchar('firebase_uid', { length: 255 }).notNull().unique(),
  email: varchar('email', { length: 255 }).notNull(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  emailVerified: boolean('email_verified').default(false),
  candidateId: integer('candidate_id').references(() => candidates.id),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const auditions = pgTable('auditions', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  title: varchar('title', { length: 255 }).notNull(),
  companyDraftId: integer('company_draft_id').references(() => companyAuditionDrafts.id),
  status: varchar('status', { length: 50 }).default('draft'),
  vibeEventId: varchar('vibe_event_id', { length: 255 }),
  round1Open: boolean('round1_open').default(false),
  round2Open: boolean('round2_open').default(false),
  publishedAt: timestamp('published_at'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const auditionRegistrations = pgTable('audition_registrations', {
  id: serial('id').primaryKey(),
  auditionId: integer('audition_id').references(() => auditions.id).notNull(),
  candidateUserId: integer('candidate_user_id').references(() => candidateUsers.id).notNull(),
  vibeParticipantId: varchar('vibe_participant_id', { length: 255 }),
  registrationStatus: varchar('registration_status', { length: 50 }).default('registered'),
  registeredAt: timestamp('registered_at').defaultNow(),
});

export const auditionRounds = pgTable('audition_rounds', {
  id: serial('id').primaryKey(),
  auditionId: integer('audition_id').references(() => auditions.id).notNull(),
  roundNumber: integer('round_number').notNull(),
  vibeAssessmentId: varchar('vibe_assessment_id', { length: 255 }),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  startTime: timestamp('start_time'),
  endTime: timestamp('end_time'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const auditionSubmissions = pgTable('audition_submissions', {
  id: serial('id').primaryKey(),
  registrationId: integer('registration_id').references(() => auditionRegistrations.id).notNull(),
  roundId: integer('round_id').references(() => auditionRounds.id).notNull(),
  vibeSubmissionId: varchar('vibe_submission_id', { length: 255 }),
  repoUrl: text('repo_url'),
  status: varchar('status', { length: 50 }).notNull().default('pending'),
  score: integer('score'),
  submittedAt: timestamp('submitted_at').defaultNow(),
});

export const submissionReviews = pgTable('submission_reviews', {
  id: serial('id').primaryKey(),
  submissionId: integer('submission_id').references(() => auditionSubmissions.id).notNull(),
  reviewerId: integer('reviewer_id').references(() => juryMembers.id).notNull(),
  scoreCriteria: jsonb('score_criteria'),
  finalScore: integer('final_score').notNull(),
  feedback: text('feedback'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const leaderboardSnapshots = pgTable('leaderboard_snapshots', {
  id: serial('id').primaryKey(),
  auditionId: integer('audition_id').references(() => auditions.id).notNull(),
  snapshotData: jsonb('snapshot_data').notNull(),
  generatedAt: timestamp('generated_at').defaultNow(),
});
